/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 -k --transform public/models/knife-baked.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/knife-baked-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[0, 0.051, 0]} rotation={[3.117, -0.113, 2.927]} scale={0.126}>
          <group name="Armature" position={[-0.043, -0.226, -0.074]} rotation={[3.126, 0.118, 3.139]} scale={0.101}>
            <primitive object={nodes.Bone} />
            <primitive object={nodes.neutral_bone} />
            <skinnedMesh name="node1" geometry={nodes.node1.geometry} material={materials.MergedBake_Baked} skeleton={nodes.node1.skeleton} />
          </group>
          <mesh name="node2" geometry={nodes.node2.geometry} material={materials.MergedBake_Baked} position={[-0.004, 0.017, 0]} rotation={[-1.571, 1.536, -3.142]} scale={10.712}>
            <mesh name="D2_logo" geometry={nodes.D2_logo.geometry} material={materials.MergedBake_Baked} position={[-0.008, -0.005, -0.007]} rotation={[0.002, 0.019, -3.139]} scale={0.003} />
            <mesh name="node25" geometry={nodes.node25.geometry} material={materials.MergedBake_Baked} />
          </mesh>
          <mesh name="node0" geometry={nodes.node0.geometry} material={materials.MergedBake_Baked} position={[-0.004, 0.017, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={10.712} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/knife-baked-transformed.glb')
