export const TESTING = true;
export const CONTROLS = false;
export const ORBIT = false;
export const TRIGGER = '.start-trigger';
export const END_TRIGGER = '.end-trigger';
export const START = 'bottom top';
export const END = 'top bottom';
//export const KNIFE_PATH = 'https://wesn.com/cdn/shop/t/49/assets/knife.glb';
export const KNIFE_PATH = 'models/knife-baked-v2-transformed.glb';
